### ISSUE TITLE
It would be nice to extract guidelines-based styles to a separate gem

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#1] opened 2017-02-20 05:04 UTC
Since we are going to use them for other projects as well

**Comment by query-string** [comment] 2017-02-20 06:14
Or perhaps wrapping styles into npm-package will be better in this case...

**Comment by skatkov** [comment] 2017-02-20 08:36
@query-string yeah, i was thinking about this too -) but the problem is, we need it for sinatra, rails and npm in this case. So let's leave it for later :)

I would create an issue in sep-guidelines, not here though -)

**Comment by query-string** [comment] 2017-02-20 08:37
Yeah, it was more like a reminder to self )

On Mon, Feb 20, 2017 at 15:36 Stanislav Katkov

<
mailto:Stanislav Katkov <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/query-string
yeah, i was thinking about this too -) but the problem is, we need it for sinatra, rails and npm in this case. So let's leave it for later :)

I would create an issue in sep-guidelines, not here though -)

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/saberespoder/sepcontent-v2/issues/1#issuecomment-281017661
, or

**Comment by skatkov** [comment] 2017-02-28 09:30
I created corresponding issues in sep-guideliness
https://github.com/saberespoder/sep-guidelines/issues

closing this issue.

**Closed as completed by skatkov** 2017-02-28 09:30 UTC
Labels: improvement
